### ISSUE TITLE
param "15 minutes" war end prepar

### ISSUE THREAD

**Issue by jsal** [XtremeOwnage/WarBot#40]
15 minutes is not enough to indicate that war preparation is complete.
Idea :
set this value as parameter ?

**Comment by XtremeOwnageDotCom** [comment]
The problem is that the schedules are currently implemented as a global, for everybody using the bot.

If we set a schedule per clan, it will end up increasing the overall resource usage for the bot by a bit. That would turn out to be an extra 200 or so threads waiting.

Although, one way to work around this, is to set multiple global schedules for war prep ending, at 15m, 30m, and 1h, and let individual clans decide which of the three options they prefer.

**Comment by jsal** [comment]
Yes i think it's the best solution.

**Comment by Naxos84** [comment]
Is it possible to add something like this to the beginning too?

because if the war starts and users get notified the waypoints might still not be described ingame.

so something like
2h before warbegin
1.5h before warbegin

**Comment by XtremeOwnageDotCom** [comment]
> Is it possible to add something like this to the beginning too?
> 
> because if the war starts and users get notified the waypoints might still not be described ingame.
> 
> so something like
> 2h before warbegin
> 1.5h before warbegin

Its possible- but, the current problem with implantation-

The current job scheduler's storage is not configured to be persistent, due to limited options for storage.

So, if/WHEN the api has issues, causing the bot to restart, there is the potential the guild will not receive the notifications at all.

However- one option- is to create multiple global schedules for 1h before, 15m before, 30m before, and allow the user to select one or many options.
