### ISSUE TITLE
Add clearing portal messages when portal closes, same as war messages

### ISSUE THREAD

**Issue by no1here2** [XtremeOwnage/WarBot#51]
**Is your feature request related to a problem? Please describe.**

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by XtremeOwnageDotCom** [comment]
So- this ticket isn't setting completely un-answered.....

Since I have not been using discord much, and nobody has been giving any feedback whatsoever of the status of the bot, this ticket will sit around idle until I accumulate enough requests/ideas/problems, and the will to start updating the source code- OR, until somebody else determines they would like to sit down and publish a pull request with the feature implemented.


But- it is a good idea- for the record.

**Comment by XtremeOwnageDotCom** [comment]
This was never completed, because the duration a portal is open, is not a consistent time. 

With war events, these are easy to trigger events for, as we know the exact timing more or less. For portal events, we only know the end time.

**Comment by XtremeOwnageDotCom** [comment]
A tad old, but, closing this ticket with dev release 4.1.4

https://docs.warbot.dev/Changelogs/v4.0/v4.1.4/

Does add the ability to clear the channel after a current maximum, of one day.
